### ISSUE TITLE
Consider adding `Flutter Web is not SEO friendly`

### ISSUE THREAD

**Issue by iapicca** [osaxma/FlutterWebLimitations#2]
I believe this is a major limitation,
consider adding the following

```
## Flutter Web is not SEO friendly

Flutter Web is not SEO friendly [see flutter/issues/46789](https://github.com/flutter/flutter/issues/46789)
making it hard, if even possible, to motetize with ADS [see flutter/issues/40376](https://github.com/flutter/flutter/issues/40376)
```

**Comment by osaxma** [comment]
Thank you @iapicca .. I've merged your pull request.

**Comment by iapicca** [comment]
I think is very useful to keep track what needs to be improved on flutter web
great idea

**Comment by osaxma** [comment]
Thanks to @rydmike for the idea. 

He also brought some good points under this issue if you're interested to follow the discussions:

https://github.com/dart-lang/sdk/issues/44876
