### ISSUE TITLE
Consider adding `Flutter Web does not support "grpc-dart"`

### ISSUE THREAD

**Issue by iapicca** [osaxma/FlutterWebLimitations#9]
flutter web does not support [grpc](https://github.com/flutter/flutter/issues/48054) https://github.com/flutter/flutter/issues/48054
alternative https://github.com/sigurdm/grpc_web_flutter_example

this package doesn't figure in the [List of dart sdk libraries not available in Flutter Web](flutter/flutter/39998)

**Comment by osaxma** [comment]
Thank you @iapicca!
